server {
    listen 80;
    listen [::]:80;
    server_name apt.example.com;

    access_log /var/log/nginx/whawty-aptrepo_access.log;
    error_log /var/log/nginx/whawty-aptrepo_error.log;

    location / {
        root /usr/local/share/whawty/aptrepo;
        index index.html;
    }
    location = /repo.json {
        root /srv/apt/repo;
    }
    location /dists/ {
        root /srv/apt/repo/;
        autoindex on;

        types {
            application/gzip  gz;
            application/zstd  zstd;
            application/x-xz  xz;
        }
        default_type text/plain;
    }
    location /pool/ {
        root /srv/apt/repo/;
        autoindex on;
    }
}
